name: datastore_dart
version: 1.0.1
description: "Google Cloud Datastore driver for Dart. Inspired by mongo_dart."
repository: https://github.com/adrianjagielak/datastore_dart

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  googleapis: '>=5.0.1 <11.0.0'
  googleapis_auth: ^1.3.1
  meta: ^1.3.0
